version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - db
        env_file:
            - .env
        environment:
            - DB_HOST=db
        volumes:
            - ./src:/app/src

    db:
        image: postgres:latest
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}

volumes:
    db-data:
